from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin


admin.autodiscover()


urlpatterns = patterns('',
    # admin
    url(r"^admin/download/downloadlink/", include("scrapyorg.download.urls")),
    url(r'^admin/(.*)', admin.site.root),

    # pablo: disabled documentation until we improve its usability. for now,
    # documentation will be served at http://doc.scrapy.org using static html
    # files generated by Sphinx, and a small notice landing page will be shown
    # in scrapy.org/doc
    # docs
#    url(r"^docs/", include("scrapyorg.docs.urls")),
    url(r"docs/.*", 'django.views.generic.simple.redirect_to', {'url': '/doc/'}),
    # news
    url(r"^news/", include("scrapyorg.blog.urls")),
)


if settings.DEBUG: # devel
    urlpatterns += patterns('',         
        (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL[1:],
          'django.views.static.serve',
          {'document_root': settings.MEDIA_ROOT}),
    )
    
# last resort, it's an article
urlpatterns += patterns('',         
    url(r"", include("scrapyorg.article.urls")),
)

