"""
Configuration file holding a dynamic global variable for the ad-hoc code coverage tool.
Source: https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules
"""
__author__ = "Felix Liljefors"

BRANCHES = [False] * 200
BRANCH_LIST_NAME = 'BRANCHES'
BRANCH_COUNT = 0


def branch_coverage_summary(num_branches):
    """Print branch coverage metrics generated by ad-hoc coverage tool"""
    taken = 0
    print('------- Branch coverage summary -------\n')
    for i in range(num_branches):
        taken += 1 if BRANCHES[i] else 0
        print(f'Branch {i} taken: {BRANCHES[i]}')
    print(f'\nTotal branch coverage: {100 * (float(taken)/num_branches)}%')
